version: '3.0'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - postgresDB
    networks:
      - postgres
    volumes:
      - ./src:/app/src 

  postgresDB:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always

networks:
  postgres:
    driver: bridge 

