version: '3.0'

services:
  server:
    image: vpk-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    image: postgres:15.1
    env_file:
      - .docker-db.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge 

