version: '3.0'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - postgres
    volumes:
      - ./src:/app/src 

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: postgres
      POSTGRES_DB: vpk-db
    ports:
      - "5433:5433"
    networks:
      - postgres

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1111
    ports:
      - "5050:80"

networks:
  postgres:
    driver: bridge