version: '3.0'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - postgres
    volumes:
      - ./src:/app/src 

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: vpk-db
    ports:
      - 5432:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge 

